import { library } from '@fortawesome/fontawesome-svg-core'
import { faGithub, faSquareFigma } from '@fortawesome/free-brands-svg-icons'
import {
  faBook,
  faBriefcase,
  faChartSimple,
  faCheck,
  faCode,
  faEnvelope,
  faFile,
  faGraduationCap,
  faHeadphones,
  faHouse,
  faLaptopCode,
  faLightbulb,
  faLink,
  faLocationDot,
  faPen,
  faScrewdriverWrench,
  faSuitcase,
  faUser,
  faWandMagicSparkles,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faGithub,
  faSquareFigma,
  faBook,
  faBriefcase,
  faChartSimple,
  faCheck,
  faCode,
  faEnvelope,
  faFile,
  faGraduationCap,
  faHeadphones,
  faHouse,
  faLaptopCode,
  faLightbulb,
  faLink,
  faLocationDot,
  faPen,
  faScrewdriverWrench,
  faSuitcase,
  faUser,
  faWandMagicSparkles,
)
